// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP7P7JOzHSk5mMmC8qGWyTyC-1o6jljs4',
    appId: '1:483005818690:web:580801a9c4dcf7a4c0cadb',
    messagingSenderId: '483005818690',
    projectId: 'fir-todo-9b24e',
    authDomain: 'fir-todo-9b24e.firebaseapp.com',
    storageBucket: 'fir-todo-9b24e.appspot.com',
    measurementId: 'G-14LX2Y1Z2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLdq3M2NilvpRS-CvOdT_I8Ez4xVPHKhU',
    appId: '1:483005818690:android:9de399afcf7b9128c0cadb',
    messagingSenderId: '483005818690',
    projectId: 'fir-todo-9b24e',
    storageBucket: 'fir-todo-9b24e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBhwdrdDN9yd-EDRyqUfYtlOxPchU-rZE',
    appId: '1:483005818690:ios:903df1e56444f68fc0cadb',
    messagingSenderId: '483005818690',
    projectId: 'fir-todo-9b24e',
    storageBucket: 'fir-todo-9b24e.appspot.com',
    iosBundleId: 'com.example.todoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBhwdrdDN9yd-EDRyqUfYtlOxPchU-rZE',
    appId: '1:483005818690:ios:049b176f04d8c8a5c0cadb',
    messagingSenderId: '483005818690',
    projectId: 'fir-todo-9b24e',
    storageBucket: 'fir-todo-9b24e.appspot.com',
    iosBundleId: 'com.example.todoFirebase.RunnerTests',
  );
}
